a = int(input("enter the first number : "))
b = int(input ("enter the second number : "))
addition = int(a+b)
subtraction = int(a-b)
multiplication = int(a*b)
division = float(a/b)
print(addition)
print(subtraction)
print(multiplication)
print(division)

c = input("enter your first name :  ")
d = input("enter your last name :   ")
print('Hello, ' + c +  d +'!' + ' Welcome to the python program' )

